import React from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "./layout.module.scss";
import NavigationBar from "./navigation";

interface Props {
  variant?: string;
  children: React.ReactNode;
}

const Layout = ({ variant, children }: Props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Loctineer Bookings</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavigationBar />

      <main className={variant}>{children}</main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Layout;
