import React from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "./layout.module.scss";
import NavigationBar from "./navigation";

interface Props {
  variant?: string;
  children: React.ReactNode;
}

const Layout = ({ variant, children }: Props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Loctineer Bookings</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavigationBar />

      <main className={variant}>{children}</main>

      <footer className={styles.footer}>
        <p>Copyright © 2022 Loctineer Ottawa - All Rights Reserved.</p>
        <p>
          Designed & Developed by {' '}
          <a
            href="https://ifedaviid.com"
            target="_blank"
            rel="noopener noreferrer"
          >
            IfeDaviid
          </a>
        </p>
      </footer>
    </div>
  );
};

export default Layout;
